# Generated by Django 3.0.7 on 2020-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sites_rank_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_name', models.CharField(max_length=200, verbose_name='Name')),
                ('locale_x', models.FloatField(verbose_name='Locale X')),
                ('locale_y', models.FloatField(verbose_name='Locale Y')),
            ],
        ),
        migrations.RenameModel(
            old_name='Siralama',
            new_name='Rank',
        ),
    ]
