# Generated by Django 3.0.7 on 2020-06-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200629_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
            preserve_default=False,
        ),
    ]
