# Generated by Django 3.0.7 on 2020-06-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rank_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('tag', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLocationCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='SearchLocationCauntry',
        ),
        migrations.RenameField(
            model_name='searchlocationcauntry',
            old_name='locale_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='searchlocationcauntry',
            old_name='locale_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='searchlocationcauntry',
            old_name='locale_y',
            new_name='y',
        ),
        migrations.RenameModel(
            old_name='Rank',
            new_name='SearchRank',
        ),
        migrations.AlterField(
            model_name='searchrank',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SearchLocationCity'),
        ),
    ]
