# Generated by Django 3.0.7 on 2020-06-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200629_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='site',
        ),
        migrations.DeleteModel(
            name='SearchLanguage',
        ),
        migrations.DeleteModel(
            name='SearchLocationCauntry',
        ),
        migrations.RemoveField(
            model_name='searchrank',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='searchrank',
            name='location',
        ),
        migrations.RemoveField(
            model_name='searchrank',
            name='site',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='SearchLocationCity',
        ),
        migrations.DeleteModel(
            name='SearchRank',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
