# Generated by Django 3.0.7 on 2020-06-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Keyword')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Add Date')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('tag', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLocationCauntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('x', models.FloatField(verbose_name='Locale X')),
                ('y', models.FloatField(verbose_name='Locale Y')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLocationCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User ID')),
                ('site_url', models.CharField(max_length=100, verbose_name='Site URL')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Add Date')),
                ('rank_time', models.IntegerField(verbose_name='Rank Time')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Add Date')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_serp.Keywords')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_serp.SearchLocationCity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_serp.Sites')),
            ],
        ),
        migrations.AddField(
            model_name='keywords',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_serp.Sites'),
        ),
    ]
