# Generated by Django 3.0.7 on 2020-07-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serp', '0003_auto_20200711_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateLocation',
            new_name='LocationPrivate',
        ),
    ]
