# Generated by Django 3.0.7 on 2020-07-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_serp', '0004_auto_20200711_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=500, verbose_name='User Agent')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_serp.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_serp.Platform'),
            preserve_default=False,
        ),
    ]
